version: "2"
run:
  tests: false
linters:
  disable:
    - unused
    - errcheck
    - ineffassign
  settings:
    staticcheck:
      checks:
        - "-ST1001" # Disalbe `ST1001` should not use dot imports
        # - "-SA4006" # Disable `SA4006` this value of err is never used
        # - "-QF1003" # Disable `QF1003` could use tagged switch on x
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - generated$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - generated$
