package helper

import (
	"github.com/alivers/anchor-go/internal/generator/model"
	. "github.com/dave/jennifer/jen"
)

func NewGoFile(ctx *model.GenerateCtx) *File {
	file := NewFile(ctx.PkgName)
	// Set a prefix to avoid collision between variable names and packages:
	file.PackagePrefix = "ag"

	file.HeaderComment("Code generated by https://github.com/alivers/anchor-go/internal. DO NOT EDIT.")

	return file
}
